package org.egov.model;
// Generated Oct 23, 2012 4:43:45 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

/**
 * Citizen generated by hbm2java
 */
@Entity
@Table(name = "citizen", uniqueConstraints = @UniqueConstraint(columnNames = "te"))
public class Citizen implements java.io.Serializable {

	private int id;
	private String te;
	private String name;
	private String email;
	private Integer active;
	private String passwd;

	public Citizen() {
	}

	public Citizen(int id) {
		this.id = id;
	}
	public Citizen(int id, String te, String name, String email,
			Integer active, String passwd) {
		this.id = id;
		this.te = te;
		this.name = name;
		this.email = email;
		this.active = active;
		this.passwd = passwd;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "te", unique = true, length = 20)
	@Size(max = 20)
	public String getTe() {
		return this.te;
	}

	public void setTe(String te) {
		this.te = te;
	}

	@Column(name = "name", length = 120)
	@Size(max = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 50)
	@Size(max = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "passwd", length = 32)
	@Size(max = 32)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

}
