package org.egov.model;
// Generated Oct 23, 2012 4:43:45 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * Tentativa generated by hbm2java
 */
@Entity
@Table(name = "tentativa")
public class Tentativa implements java.io.Serializable {

	private int id;
	private String name;
	private String description;

	public Tentativa() {
	}

	public Tentativa(int id) {
		this.id = id;
	}
	public Tentativa(int id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 120)
	@Size(max = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
